### ISSUE TITLE
标注异常

### ISSUE THREAD

**Issue by zhedahe** [PaddlePaddle/EasyData#26]
感谢开发者提供的工具，很好用。
不过我发现一个问题：如果图像尺寸较大，比如3072x4096，使用 eiseg 标注开始自动进入 宫格 模式，标注完发现mask图像最右侧有一条宽宽的黑线，我检查了原图和各个宫格图，发现载入图像时，软件会自动裁掉图像最右侧一部分，导致标注时这一部分不在宫格内，进而导致mask图像最右侧有一条竖线。
我使用的是EISeg 1.1 版本，windows 平台

**Comment by cuicheng01** [comment]
您提到的问题和该repo没有关系哈，建议您直接找EISeg，该issue关闭了
